# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b2beb18816ba573598e8e4ca1c987f31569dc52724d42f2d7500fd2bb8e76a38dac246089272240f8ff55cb78db545b0f611c5f3db218c55e94419065cda0e5

test:
  secret_key_base: ab382ab9e7d4f765c506a9de5f87d6f6a2eb1a032cc7c45000e706277f6c6afaee0e51b289f6920f095f03005415621a1a431456138d79af32203dcc9d9ba468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
